name: Go

on: 
  workflow_dispatch:
    inputs:
      build_type:
        description: 'The type of build to perform'
        required: true
        default: 'debug'
      version:
        description: 'The version to build'
        required: false
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -v ./...

    - name: Final
      run: |
        echo "Build type: ${{ github.event.inputs.build_type }}"
        echo "Version: ${{ github.event.inputs.version }}"
